# Test your FastAPI endpoints

POST http://127.0.0.1:8081/api/classify
Accept: application/json
Content-Type: application/json

{
  "text": "Make an image of a banana",
  "labels": ["search", "image generation", "code"]
}

###